baseurl = "https://conoroneill.com/"
languageCode = "en-us"
title = "Conor's Bandon Blog"
theme = "casper"
Paginate = 10
disqusShortname = "conorbandon"
# rssuri = "atom.xml"
rssLimit = 20
publishdir = "docs"

[permalinks]
  post="/:year/:month/:day/:slug/"

[params]
  githubName = "conoro"
  linkedinName = "conoroneill"
  description = "Running, Food and Local stuff from a blow-in"
  google_analytics = "UA-88610-1"
  cover = "images/chetwynd_bw.jpg"
  author = "Conor O'Neill"
  authorlocation = "Bandon, Cork, Ireland"
  authorwebsite = "https://conoroneill.com"
  bio= "Tech guy who likes running slowly"
  logo = "images/conors_bandon_blog.png"
  googleAnalyticsUserID = "UA-88610-1"
  # RSSLink = "atom.xml"
